In [ ]:
import os
import numpy as np
import tensorflow as tf

In [ ]:
x = np.random.sample((100, 3))
tf.debugging.set_log_device_placement(True)     # 각 텐서와 연산이 어떠한 장치에 할당되었는지 출력하기
data_set = tf.data.Dataset.from_tensor_slices(x)
print(data_set)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op TensorSliceDataset in device /job:localhost/replica:0/task:0/device:CPU:0
<TensorSliceDataset element_spec=TensorSpec(shape=(3,), dtype=tf.float64, name=None)>


In [ ]:
# 텐서 생성
a = tf.constant([
    [1, 1],
    [2, 2]
])

b = tf.constant([
    [5, 6],
    [7, 8]
])

c = tf.matmul(a, b)
print(c)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[12 14]
 [24 28]], shape=(2, 2), dtype=int32)


In [ ]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 16873381632723223611
 xla_global_id: -1, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 14415560704
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 12543025398864106046
 physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"
 xla_global_id: 416903419]

In [19]:
import torch
tensor = torch.rand(3,2)


In [20]:
from torch.cuda import is_available
# 속성 변경
tensor = tensor.reshape(2,3)
tensor = tensor.int()
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([2, 3])
Datatype of tensor : torch.int32
Device tensor is stored on : cuda:0


In [22]:
x = torch.tensor([[1,2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5,6], [7, 8]], dtype=torch.float32)

# in-place 연산
print(x.add(y))
print(x)

print(x.add_(y))
print(x)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])
