In [1]:
import torch

In [2]:
from torch._C import device
print(torch.tensor([[1, 2],[3, 4]], device="cuda:0"))

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [ ]:
data= [
    [1, 2],
    [3, 4]
]

x = torch.tensor(data)
print(x.is_cuda)          # GPU 사용 여부 체크하기

False


In [ ]:
# GPU로 옮기기
x = x.cuda()
print(x.is_cuda)

True


In [ ]:
# CPU로 옮기기
x = x.cpu()
print(x.is_cuda)

False


In [ ]:
# GPU 장치의 텐서
a = torch.tensor([
    [1, 1],
    [2, 2]
]).cuda()

# CPU 장치의 텐서
b = torch.tensor([
    [5, 6],
    [7, 8]
])

#print(torch.matmul(a, b))     # 오류 발생
print(torch.matmul(a.cpu(), b))

tensor([[12, 14],
        [24, 28]])


In [ ]:
tensor = torch.rand(3, 4)
print(tensor)
print(f"Sjape : {tensor.shape}")
print(f"Data tpye : {tensor.dtype}")
print(f"Device : {tensor.device}")

tensor([[0.8438, 0.3626, 0.6669, 0.6556],
        [0.3139, 0.0720, 0.2443, 0.6893],
        [0.6601, 0.4676, 0.0616, 0.2464]])
Sjape : torch.Size([3, 4])
Data tpye : torch.float32
Device : cpu


In [3]:
print(torch.__version__)

1.13.0+cu116
